FROM kalilinux/kali-rolling

ARG DEBIAN_FRONTEND=noninteractive

RUN git clone https://github.com/benrau87/os-scripts && cd os-scripts && chmod +x 2020-kali.sh

RUN ./2020-kali.sh

CMD /usr/sbin/xrdp-sesman;/usr/sbin/xrdp -n
